// <auto-generated />
using System;
using IK.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IK.Web.Migrations
{
    [DbContext(typeof(HumanResourcesDbContext))]
    [Migration("20260724124154_AddEmployeeFiles")]
    partial class AddEmployeeFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IK.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<DateTimeOffset>("ActionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionDate");

                    b.HasIndex("ActionType");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_ActionType", "[ActionType] BETWEEN 1 AND 24");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RegionManagerEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("RegionManagerEmployeeId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("KktcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("KKTC_KimlikNo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("KktcKimlikNo")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocument", b =>
                {
                    b.Property<long>("EmployeeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeDocumentId"));

                    b.Property<string>("CategoryCanonicalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeDocumentId");

                    b.HasIndex("CategoryCanonicalKey");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "CategoryCanonicalKey", "UploadedAt");

                    b.ToTable("EmployeeDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDocuments_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocumentCategory", b =>
                {
                    b.Property<string>("CanonicalKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CanonicalKey");

                    b.ToTable("EmployeeDocumentCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDocumentCategories_CanonicalKey", "[CanonicalKey] <> '' AND [CanonicalKey] COLLATE Latin1_General_100_BIN2 = LOWER([CanonicalKey]) AND [CanonicalKey] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^a-z0-9-]%' AND [CanonicalKey] NOT LIKE '-%' AND [CanonicalKey] NOT LIKE '%-' AND [CanonicalKey] NOT LIKE '%--%'");
                        });

                    b.HasData(
                        new
                        {
                            CanonicalKey = "identity",
                            DisplayName = "Kimlik Belgeleri",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            CanonicalKey = "employment",
                            DisplayName = "İş ve Sözleşme Belgeleri",
                            IsActive = true,
                            SortOrder = 20
                        },
                        new
                        {
                            CanonicalKey = "education",
                            DisplayName = "Eğitim ve Sertifika Belgeleri",
                            IsActive = true,
                            SortOrder = 30
                        },
                        new
                        {
                            CanonicalKey = "health",
                            DisplayName = "Sağlık Belgeleri",
                            IsActive = true,
                            SortOrder = 40
                        },
                        new
                        {
                            CanonicalKey = "other",
                            DisplayName = "Diğer Belgeler",
                            IsActive = true,
                            SortOrder = 50
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeProfilePhoto", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("EmployeeProfilePhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeProfilePhotos_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ApproverRole")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DecisionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("RequestId", "ApproverRole")
                        .IsUnique();

                    b.ToTable("LeaveApprovals");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<decimal>("CarryOverDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("CarryOverLimitWarningConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CarryOverLimitWarningConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CarryOverLimitWarningConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EntitledDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("Year");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RequestId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ManagerApproverEmployeeId");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<decimal>("AnnualQuota")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("CarryOverRule")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxAccrualDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("LeaveTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.HasOne("IK.Web.Models.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "RegionManager")
                        .WithMany()
                        .HasForeignKey("RegionManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentDepartment");

                    b.Navigation("RegionManager");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.HasOne("IK.Web.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocument", b =>
                {
                    b.HasOne("IK.Web.Models.EmployeeDocumentCategory", "Category")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryCanonicalKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeProfilePhoto", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithOne("ProfilePhoto")
                        .HasForeignKey("IK.Web.Models.EmployeeProfilePhoto", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveApproval", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.LeaveRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverEmployee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "ManagerApprover")
                        .WithMany()
                        .HasForeignKey("ManagerApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("ManagerApprover");
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("Documents");

                    b.Navigation("ProfilePhoto");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocumentCategory", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
