// <auto-generated />
using System;
using IK.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IK.Web.Migrations
{
    [DbContext(typeof(HumanResourcesDbContext))]
    [Migration("20260727111934_EnforceEmployeeDocumentRelatedOwnership")]
    partial class EnforceEmployeeDocumentRelatedOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IK.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<DateTimeOffset>("ActionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionDate");

                    b.HasIndex("ActionType");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_ActionType", "[ActionType] BETWEEN 1 AND 24");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RegionManagerEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("RegionManagerEmployeeId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("KktcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("KKTC_KimlikNo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("KktcKimlikNo")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeAddress", b =>
                {
                    b.Property<int>("EmployeeAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeAddressId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeAddresses_EmployeeId_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeeAddresses");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeBankAccount", b =>
                {
                    b.Property<int>("EmployeeBankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeBankAccountId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeBankAccountId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Iban")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeBankAccounts_EmployeeId_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeeBankAccounts");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeCourseCertificate", b =>
                {
                    b.Property<int>("EmployeeCourseCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCourseCertificateId"));

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingOrganization")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeCourseCertificateId");

                    b.HasAlternateKey("EmployeeId", "EmployeeCourseCertificateId")
                        .HasName("AK_EmployeeCourseCertificates_EmployeeId_RecordId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCourseCertificates");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocument", b =>
                {
                    b.Property<long>("EmployeeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeDocumentId"));

                    b.Property<string>("CategoryCanonicalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeCourseCertificateId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeEducationId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeIdentityDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeDocumentId");

                    b.HasIndex("CategoryCanonicalKey");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "EmployeeCourseCertificateId");

                    b.HasIndex("EmployeeId", "EmployeeEducationId");

                    b.HasIndex("EmployeeId", "EmployeeIdentityDocumentId");

                    b.HasIndex("EmployeeId", "CategoryCanonicalKey", "UploadedAt");

                    b.ToTable("EmployeeDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDocuments_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocumentCategory", b =>
                {
                    b.Property<string>("CanonicalKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CanonicalKey");

                    b.ToTable("EmployeeDocumentCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDocumentCategories_CanonicalKey", "[CanonicalKey] <> '' AND [CanonicalKey] COLLATE Latin1_General_100_BIN2 = LOWER([CanonicalKey]) AND [CanonicalKey] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^a-z0-9-]%' AND [CanonicalKey] NOT LIKE '-%' AND [CanonicalKey] NOT LIKE '%-' AND [CanonicalKey] NOT LIKE '%--%'");
                        });

                    b.HasData(
                        new
                        {
                            CanonicalKey = "identity",
                            DisplayName = "Kimlik Belgeleri",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            CanonicalKey = "employment",
                            DisplayName = "İş ve Sözleşme Belgeleri",
                            IsActive = true,
                            SortOrder = 20
                        },
                        new
                        {
                            CanonicalKey = "education",
                            DisplayName = "Eğitim ve Sertifika Belgeleri",
                            IsActive = true,
                            SortOrder = 30
                        },
                        new
                        {
                            CanonicalKey = "health",
                            DisplayName = "Sağlık Belgeleri",
                            IsActive = true,
                            SortOrder = 40
                        },
                        new
                        {
                            CanonicalKey = "other",
                            DisplayName = "Diğer Belgeler",
                            IsActive = true,
                            SortOrder = 50
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeEducation", b =>
                {
                    b.Property<int>("EmployeeEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeEducationId"));

                    b.Property<string>("Degree")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsGraduated")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeEducationId");

                    b.HasAlternateKey("EmployeeId", "EmployeeEducationId")
                        .HasName("AK_EmployeeEducations_EmployeeId_RecordId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeIdentityDocument", b =>
                {
                    b.Property<int>("EmployeeIdentityDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeIdentityDocumentId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("EmployeeIdentityDocumentId");

                    b.HasAlternateKey("EmployeeId", "EmployeeIdentityDocumentId")
                        .HasName("AK_EmployeeIdentityDocuments_EmployeeId_RecordId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("EmployeeIdentityDocuments");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeePhone", b =>
                {
                    b.Property<int>("EmployeePhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeePhoneId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EmployeePhoneId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeePhones_EmployeeId_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeePhones");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeProfilePhoto", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("EmployeeProfilePhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeProfilePhotos_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeTermination", b =>
                {
                    b.Property<int>("EmployeeTerminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTerminationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("TerminationDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeTerminationId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeTerminations");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ApproverRole")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DecisionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("RequestId", "ApproverRole")
                        .IsUnique();

                    b.ToTable("LeaveApprovals");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<decimal>("CarryOverDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("CarryOverLimitWarningConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CarryOverLimitWarningConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CarryOverLimitWarningConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EntitledDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("Year");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RequestId");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ManagerApproverEmployeeId");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<decimal>("AnnualQuota")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("CarryOverRule")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxAccrualDays")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("LeaveTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.HasOne("IK.Web.Models.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "RegionManager")
                        .WithMany()
                        .HasForeignKey("RegionManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentDepartment");

                    b.Navigation("RegionManager");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.HasOne("IK.Web.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeAddress", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeBankAccount", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("BankAccounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeCourseCertificate", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("CourseCertificates")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocument", b =>
                {
                    b.HasOne("IK.Web.Models.EmployeeDocumentCategory", "Category")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryCanonicalKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.EmployeeCourseCertificate", "CourseCertificate")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId", "EmployeeCourseCertificateId")
                        .HasPrincipalKey("EmployeeId", "EmployeeCourseCertificateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.EmployeeEducation", "Education")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId", "EmployeeEducationId")
                        .HasPrincipalKey("EmployeeId", "EmployeeEducationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.EmployeeIdentityDocument", "IdentityDocument")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId", "EmployeeIdentityDocumentId")
                        .HasPrincipalKey("EmployeeId", "EmployeeIdentityDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CourseCertificate");

                    b.Navigation("Education");

                    b.Navigation("Employee");

                    b.Navigation("IdentityDocument");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeEducation", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Educations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeIdentityDocument", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("IdentityDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeePhone", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Phones")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeProfilePhoto", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithOne("ProfilePhoto")
                        .HasForeignKey("IK.Web.Models.EmployeeProfilePhoto", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeTermination", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithOne("Termination")
                        .HasForeignKey("IK.Web.Models.EmployeeTermination", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveApproval", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.LeaveRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverEmployee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "ManagerApprover")
                        .WithMany()
                        .HasForeignKey("ManagerApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("ManagerApprover");
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("CourseCertificates");

                    b.Navigation("DirectReports");

                    b.Navigation("Documents");

                    b.Navigation("Educations");

                    b.Navigation("IdentityDocuments");

                    b.Navigation("Phones");

                    b.Navigation("ProfilePhoto");

                    b.Navigation("Termination");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeCourseCertificate", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocumentCategory", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeEducation", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeIdentityDocument", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
