// <auto-generated />
using System;
using IK.Web.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IK.Web.Migrations
{
    [DbContext(typeof(HumanResourcesDbContext))]
    [Migration("20260811075943_CompletePersonnelRoleCutover")]
    partial class CompletePersonnelRoleCutover
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IK.Web.Models.ApplicationRole", b =>
                {
                    b.Property<int>("ApplicationRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationRoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ApplicationRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApplicationRoles");

                    b.HasData(
                        new
                        {
                            ApplicationRoleId = 1,
                            Description = "Standart çalışan erişimi",
                            Name = "Çalışan"
                        },
                        new
                        {
                            ApplicationRoleId = 2,
                            Description = "Departman yöneticisi erişimi",
                            Name = "Yönetici"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            Description = "İnsan kaynakları yönetimi",
                            Name = "İnsan Kaynakları"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            Description = "Tam uygulama ve personel yönetimi",
                            Name = "Sistem Yöneticisi"
                        });
                });

            modelBuilder.Entity("IK.Web.Models.ApplicationRolePermission", b =>
                {
                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApplicationRoleId", "PermissionName");

                    b.HasIndex("PermissionName");

                    b.ToTable("ApplicationRolePermissions");

                    b.HasData(
                        new
                        {
                            ApplicationRoleId = 2,
                            PermissionName = "CanViewLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 2,
                            PermissionName = "CanManageLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 2,
                            PermissionName = "CanExectuteApproveLeave"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanManageDepartments"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanManageDepartments"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanviewEmployeeSearch"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanviewEmployeeSearch"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanCreateNewEmployee"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanCreateNewEmployee"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanManageLeaveTypes"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanManageLeaveTypes"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanManagePublicHolidays"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanManagePublicHolidays"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanManageLeaveBalances"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanManageLeaveBalances"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanViewLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanViewLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanManageLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanManageLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanEditDeleteLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanEditDeleteLeaveRequests"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanExectuteApproveLeave"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanExectuteApproveLeave"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanActAsHumanResources"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanViewAuditLogs"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanViewAuditLogs"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanViewAllPersonnelInformation"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanViewAllPersonnelInformation"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanEditAllPersonnelInformation"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanEditAllPersonnelInformation"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanAccessSensitivePersonnelInformation"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanAccessSensitivePersonnelInformation"
                        },
                        new
                        {
                            ApplicationRoleId = 4,
                            PermissionName = "CanDownloadPersonnelDocuments"
                        },
                        new
                        {
                            ApplicationRoleId = 3,
                            PermissionName = "CanDownloadPersonnelDocuments"
                        },
                        new
                        {
                            ApplicationRoleId = 1,
                            PermissionName = "CanManageLeaveRequests"
                        });
                });

            modelBuilder.Entity("IK.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<DateTimeOffset>("ActionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int?>("ActorEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemActorKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActionDate");

                    b.HasIndex("ActionType");

                    b.HasIndex("ActorEmployeeId");

                    b.HasIndex("SystemActorKey");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_ActionType", "[ActionType] BETWEEN 1 AND 43");

                            t.HasCheckConstraint("CK_AuditLogs_Actor", "([ActorEmployeeId] IS NOT NULL AND [SystemActorKey] IS NULL) OR ([ActorEmployeeId] IS NULL AND [SystemActorKey] IS NOT NULL AND [SystemActorKey] <> '')");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<int?>("ActiveDelegateEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("ManagerEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RegionManagerEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId");

                    b.HasIndex("ActiveDelegateEmployeeId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("ParentDepartmentId");

                    b.HasIndex("RegionManagerEmployeeId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("KktcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("KKTC_KimlikNo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("StaffDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("KktcKimlikNo")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Employees_BloodGroup", "[BloodGroup] IS NULL OR [BloodGroup] BETWEEN 1 AND 8");

                            t.HasCheckConstraint("CK_Employees_Gender", "[Gender] IS NULL OR [Gender] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeAddress", b =>
                {
                    b.Property<int>("EmployeeAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeAddressId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeAddresses_EmployeeId_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeeAddresses");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeBankAccount", b =>
                {
                    b.Property<int>("EmployeeBankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeBankAccountId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeBankAccountId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Iban")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeBankAccounts_EmployeeId_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeeBankAccounts");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeCourseCertificate", b =>
                {
                    b.Property<int>("EmployeeCourseCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeCourseCertificateId"));

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingOrganization")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeCourseCertificateId");

                    b.HasAlternateKey("EmployeeId", "EmployeeCourseCertificateId")
                        .HasName("AK_EmployeeCourseCertificates_EmployeeId_RecordId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCourseCertificates");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocument", b =>
                {
                    b.Property<long>("EmployeeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeDocumentId"));

                    b.Property<string>("CategoryCanonicalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeCourseCertificateId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeEducationId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeIdentityDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeDocumentId");

                    b.HasIndex("CategoryCanonicalKey");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "EmployeeCourseCertificateId");

                    b.HasIndex("EmployeeId", "EmployeeEducationId");

                    b.HasIndex("EmployeeId", "EmployeeIdentityDocumentId");

                    b.HasIndex("EmployeeId", "CategoryCanonicalKey", "UploadedAt");

                    b.ToTable("EmployeeDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDocuments_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocumentCategory", b =>
                {
                    b.Property<string>("CanonicalKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("CanonicalKey");

                    b.ToTable("EmployeeDocumentCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeDocumentCategories_CanonicalKey", "[CanonicalKey] <> '' AND [CanonicalKey] COLLATE Latin1_General_100_BIN2 = LOWER([CanonicalKey]) AND [CanonicalKey] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^a-z0-9-]%' AND [CanonicalKey] NOT LIKE '-%' AND [CanonicalKey] NOT LIKE '%-' AND [CanonicalKey] NOT LIKE '%--%'");
                        });

                    b.HasData(
                        new
                        {
                            CanonicalKey = "identity",
                            DisplayName = "Kimlik Belgeleri",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            CanonicalKey = "employment",
                            DisplayName = "İş ve Sözleşme Belgeleri",
                            IsActive = true,
                            SortOrder = 20
                        },
                        new
                        {
                            CanonicalKey = "education",
                            DisplayName = "Eğitim ve Sertifika Belgeleri",
                            IsActive = true,
                            SortOrder = 30
                        },
                        new
                        {
                            CanonicalKey = "health",
                            DisplayName = "Sağlık Belgeleri",
                            IsActive = true,
                            SortOrder = 40
                        },
                        new
                        {
                            CanonicalKey = "other",
                            DisplayName = "Diğer Belgeler",
                            IsActive = true,
                            SortOrder = 50
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeEducation", b =>
                {
                    b.Property<int>("EmployeeEducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeEducationId"));

                    b.Property<string>("Degree")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsGraduated")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeEducationId");

                    b.HasAlternateKey("EmployeeId", "EmployeeEducationId")
                        .HasName("AK_EmployeeEducations_EmployeeId_RecordId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeEducations");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeIdentityDocument", b =>
                {
                    b.Property<int>("EmployeeIdentityDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeIdentityDocumentId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("EmployeeIdentityDocumentId");

                    b.HasAlternateKey("EmployeeId", "EmployeeIdentityDocumentId")
                        .HasName("AK_EmployeeIdentityDocuments_EmployeeId_RecordId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("EmployeeIdentityDocuments");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeePhone", b =>
                {
                    b.Property<int>("EmployeePhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeePhoneId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EmployeePhoneId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeePhones_EmployeeId_Primary")
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("EmployeePhones");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeProfilePhoto", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("EmployeeProfilePhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_EmployeeProfilePhotos_SizeBytes", "[SizeBytes] > 0");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeTermination", b =>
                {
                    b.Property<int>("EmployeeTerminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTerminationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly>("TerminationDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeTerminationId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeTerminations");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveApproval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ApproverRole")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DecisionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("RequestId", "ApproverRole")
                        .IsUnique();

                    b.ToTable("LeaveApprovals");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<decimal>("CarryOverDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<bool>("CarryOverLimitWarningConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CarryOverLimitWarningConfirmedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CarryOverLimitWarningConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EntitledDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BalanceId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("Year");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveBalances_HalfDayAmounts", "[EntitledDays] >= 0 AND [EntitledDays] * 2 = FLOOR([EntitledDays] * 2) AND [CarryOverDays] >= 0 AND [CarryOverDays] * 2 = FLOOR([CarryOverDays] * 2) AND [UsedDays] >= 0 AND [UsedDays] * 2 = FLOOR([UsedDays] * 2) AND [RemainingDays] >= 0 AND [RemainingDays] * 2 = FLOOR([RemainingDays] * 2) AND [RemainingDays] = [EntitledDays] + [CarryOverDays] - [UsedDays]");

                            t.HasCheckConstraint("CK_LeaveBalances_MobilizationMaximum", "[LeaveTypeId] <> 6 OR [EntitledDays] + [CarryOverDays] <= 2");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationApproval", b =>
                {
                    b.Property<int>("CancellationApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationApprovalId"));

                    b.Property<int?>("ApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ApproverRole")
                        .HasColumnType("int");

                    b.Property<int>("CancellationRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DecisionDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CancellationApprovalId");

                    b.HasIndex("ApproverEmployeeId");

                    b.HasIndex("CancellationRequestId", "ApproverRole")
                        .IsUnique();

                    b.ToTable("LeaveCancellationApprovals", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveCancellationApprovals_ApproverRole", "[ApproverRole] IN (1, 2)");

                            t.HasCheckConstraint("CK_LeaveCancellationApprovals_Decision", "[Decision] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_LeaveCancellationApprovals_RejectionComment", "[Decision] <> 3 OR NULLIF(LTRIM(RTRIM([Comment])), '') IS NOT NULL");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationBalanceRefund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<int>("BalanceId")
                        .HasColumnType("int");

                    b.Property<int>("CancellationRequestId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Days")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("RefundId");

                    b.HasIndex("BalanceId");

                    b.HasIndex("CancellationRequestId", "BalanceId", "Source")
                        .IsUnique();

                    b.ToTable("LeaveCancellationBalanceRefunds", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveCancellationBalanceRefunds_Days", "[Days] > 0 AND [Days] * 2 = FLOOR([Days] * 2)");

                            t.HasCheckConstraint("CK_LeaveCancellationBalanceRefunds_Source", "[Source] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationRequest", b =>
                {
                    b.Property<int>("CancellationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CancellationRequestId"));

                    b.Property<DateTime>("CancellationEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CancellationStartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDirectCancellation")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RequestedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RequestedRefundDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("CancellationRequestId");

                    b.HasIndex("ManagerApproverEmployeeId");

                    b.HasIndex("RequestedByEmployeeId");

                    b.HasIndex("LeaveRequestId", "CurrentStatus");

                    b.ToTable("LeaveCancellationRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveCancellationRequests_CurrentStatus", "[CurrentStatus] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_LeaveCancellationRequests_DateRange", "[CancellationStartDate] <= [CancellationEndDate]");

                            t.HasCheckConstraint("CK_LeaveCancellationRequests_RefundDays", "[RequestedRefundDays] > 0 AND [RequestedRefundDays] * 2 = FLOOR([RequestedRefundDays] * 2)");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCarryOverWarning", b =>
                {
                    b.Property<int>("WarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarningId"));

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BalanceId")
                        .HasColumnType("int");

                    b.Property<decimal>("CarryOverDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EntitledDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TotalDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WarningLimitDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("WarningId");

                    b.HasIndex("BalanceId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("IsAcknowledged", "Year");

                    b.ToTable("LeaveCarryOverWarnings", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveCarryOverWarnings_HalfDayAmounts", "[CarryOverDays] >= 0 AND [CarryOverDays] * 2 = FLOOR([CarryOverDays] * 2) AND [EntitledDays] >= 0 AND [EntitledDays] * 2 = FLOOR([EntitledDays] * 2) AND [TotalDays] >= 0 AND [TotalDays] * 2 = FLOOR([TotalDays] * 2) AND [WarningLimitDays] > 0 AND [WarningLimitDays] * 2 = FLOOR([WarningLimitDays] * 2) AND [TotalDays] = [EntitledDays] + [CarryOverDays]");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("DelegateEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsRetrospective")
                        .HasColumnType("bit");

                    b.Property<int?>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerApproverEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("RequestId");

                    b.HasIndex("Category");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("DelegateEmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ManagerApproverEmployeeId");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("LeaveRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequests_Category", "[Category] IN (1, 2)");

                            t.HasCheckConstraint("CK_LeaveRequests_CurrentStatus", "[CurrentStatus] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_LeaveRequests_HalfDayAmount", "[RequestedDays] > 0 AND [RequestedDays] * 2 = FLOOR([RequestedDays] * 2)");

                            t.HasCheckConstraint("CK_LeaveRequests_LeaveTypeSelection", "([Category] = 1 AND [LeaveTypeId] IS NULL) OR ([Category] = 2 AND [LeaveTypeId] IS NOT NULL AND [LeaveTypeId] > 0)");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequestApprovedDay", b =>
                {
                    b.Property<long>("ApprovedDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApprovedDayId"));

                    b.Property<decimal>("Days")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("ApprovedDayId");

                    b.HasIndex("RequestId", "WorkDate")
                        .IsUnique();

                    b.ToTable("LeaveRequestApprovedDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequestApprovedDays_Days", "[Days] IN (0.5, 1.0)");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequestBalanceAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<int>("BalanceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Days")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("BalanceId");

                    b.HasIndex("RequestId", "BalanceId", "Source")
                        .IsUnique();

                    b.ToTable("LeaveRequestBalanceAllocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequestBalanceAllocations_HalfDayAmount", "[Days] > 0 AND [Days] * 2 = FLOOR([Days] * 2)");

                            t.HasCheckConstraint("CK_LeaveRequestBalanceAllocations_Source", "[Source] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<decimal>("AnnualQuota")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<bool>("CarryOverRule")
                        .HasColumnType("bit");

                    b.Property<int>("EntitlementKind")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAccrualDays")
                        .HasPrecision(7, 1)
                        .HasColumnType("decimal(7,1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("LeaveTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LeaveTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveTypes_EntitlementKind", "[EntitlementKind] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_LeaveTypes_HalfDayAmounts", "[AnnualQuota] >= 0 AND [AnnualQuota] * 2 = FLOOR([AnnualQuota] * 2) AND [MaxAccrualDays] > 0 AND [MaxAccrualDays] * 2 = FLOOR([MaxAccrualDays] * 2)");

                            t.HasCheckConstraint("CK_LeaveTypes_MobilizationPolicy", "[EntitlementKind] <> 6 OR ([AnnualQuota] <= 2 AND [CarryOverRule] = 0 AND [MaxAccrualDays] <= 2)");

                            t.HasCheckConstraint("CK_LeaveTypes_PositiveId", "[LeaveTypeId] > 0");
                        });

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            AnnualQuota = 30m,
                            CarryOverRule = true,
                            EntitlementKind = 1,
                            MaxAccrualDays = 50m,
                            Name = "0-10 Yıllık Çalışan İzni"
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            AnnualQuota = 30m,
                            CarryOverRule = true,
                            EntitlementKind = 2,
                            MaxAccrualDays = 50m,
                            Name = "10-20 Yıllık Çalışan İzni"
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            AnnualQuota = 30m,
                            CarryOverRule = true,
                            EntitlementKind = 3,
                            MaxAccrualDays = 50m,
                            Name = "20-30 Yıllık Çalışan İzni"
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            AnnualQuota = 30m,
                            CarryOverRule = false,
                            EntitlementKind = 4,
                            MaxAccrualDays = 50m,
                            Name = "Hastalık İzni"
                        },
                        new
                        {
                            LeaveTypeId = 5,
                            AnnualQuota = 30m,
                            CarryOverRule = false,
                            EntitlementKind = 5,
                            MaxAccrualDays = 50m,
                            Name = "Hamilelik İzni"
                        },
                        new
                        {
                            LeaveTypeId = 6,
                            AnnualQuota = 2m,
                            CarryOverRule = false,
                            EntitlementKind = 6,
                            MaxAccrualDays = 2m,
                            Name = "Seferberlik İzni"
                        });
                });

            modelBuilder.Entity("IK.Web.Models.ManagerDelegation", b =>
                {
                    b.Property<long>("ManagerDelegationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ManagerDelegationId"));

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DelegateEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("LeaveRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerEmployeeId")
                        .HasColumnType("int");

                    b.Property<long?>("ParentManagerDelegationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("RestoredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ManagerDelegationId");

                    b.HasIndex("DelegateEmployeeId");

                    b.HasIndex("LeaveRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_ManagerDelegations_LeaveRequest")
                        .HasFilter("[LeaveRequestId] IS NOT NULL AND [RestoredAt] IS NULL");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("ParentManagerDelegationId");

                    b.HasIndex("DepartmentId", "RestoredAt");

                    b.ToTable("ManagerDelegations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagerDelegations_DateRange", "[EndDate] >= [StartDate]");
                        });
                });

            modelBuilder.Entity("IK.Web.Models.PublicHoliday", b =>
                {
                    b.Property<int>("PublicHolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicHolidayId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("PublicHolidayId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("IK.Web.Models.ApplicationRolePermission", b =>
                {
                    b.HasOne("IK.Web.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("Permissions")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "ActiveDelegateEmployee")
                        .WithMany()
                        .HasForeignKey("ActiveDelegateEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Department", "ParentDepartment")
                        .WithMany("ChildDepartments")
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "RegionManager")
                        .WithMany()
                        .HasForeignKey("RegionManagerEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveDelegateEmployee");

                    b.Navigation("Manager");

                    b.Navigation("ParentDepartment");

                    b.Navigation("RegionManager");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.HasOne("IK.Web.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("Employees")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId");

                    b.Navigation("ApplicationRole");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeAddress", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeBankAccount", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("BankAccounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeCourseCertificate", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("CourseCertificates")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocument", b =>
                {
                    b.HasOne("IK.Web.Models.EmployeeDocumentCategory", "Category")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryCanonicalKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.EmployeeCourseCertificate", "CourseCertificate")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId", "EmployeeCourseCertificateId")
                        .HasPrincipalKey("EmployeeId", "EmployeeCourseCertificateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.EmployeeEducation", "Education")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId", "EmployeeEducationId")
                        .HasPrincipalKey("EmployeeId", "EmployeeEducationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.EmployeeIdentityDocument", "IdentityDocument")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId", "EmployeeIdentityDocumentId")
                        .HasPrincipalKey("EmployeeId", "EmployeeIdentityDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CourseCertificate");

                    b.Navigation("Education");

                    b.Navigation("Employee");

                    b.Navigation("IdentityDocument");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeEducation", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Educations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeIdentityDocument", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("IdentityDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeePhone", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany("Phones")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeProfilePhoto", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithOne("ProfilePhoto")
                        .HasForeignKey("IK.Web.Models.EmployeeProfilePhoto", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeTermination", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithOne("Termination")
                        .HasForeignKey("IK.Web.Models.EmployeeTermination", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveApproval", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.LeaveRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverEmployee");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationApproval", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "ApproverEmployee")
                        .WithMany()
                        .HasForeignKey("ApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.LeaveCancellationRequest", "CancellationRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("CancellationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverEmployee");

                    b.Navigation("CancellationRequest");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationBalanceRefund", b =>
                {
                    b.HasOne("IK.Web.Models.LeaveBalance", "Balance")
                        .WithMany()
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveCancellationRequest", "CancellationRequest")
                        .WithMany("BalanceRefunds")
                        .HasForeignKey("CancellationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");

                    b.Navigation("CancellationRequest");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationRequest", b =>
                {
                    b.HasOne("IK.Web.Models.LeaveRequest", "LeaveRequest")
                        .WithMany("CancellationRequests")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "ManagerApprover")
                        .WithMany()
                        .HasForeignKey("ManagerApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "RequestedByEmployee")
                        .WithMany()
                        .HasForeignKey("RequestedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LeaveRequest");

                    b.Navigation("ManagerApprover");

                    b.Navigation("RequestedByEmployee");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCarryOverWarning", b =>
                {
                    b.HasOne("IK.Web.Models.LeaveBalance", "Balance")
                        .WithOne("CarryOverWarning")
                        .HasForeignKey("IK.Web.Models.LeaveCarryOverWarning", "BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Balance");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "DelegateEmployee")
                        .WithMany()
                        .HasForeignKey("DelegateEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "ManagerApprover")
                        .WithMany()
                        .HasForeignKey("ManagerApproverEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DelegateEmployee");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("ManagerApprover");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequestApprovedDay", b =>
                {
                    b.HasOne("IK.Web.Models.LeaveRequest", "Request")
                        .WithMany("ApprovedDays")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequestBalanceAllocation", b =>
                {
                    b.HasOne("IK.Web.Models.LeaveBalance", "Balance")
                        .WithMany("RequestAllocations")
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveRequest", "Request")
                        .WithMany("BalanceAllocations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("IK.Web.Models.ManagerDelegation", b =>
                {
                    b.HasOne("IK.Web.Models.Employee", "DelegateEmployee")
                        .WithMany("DelegateAssignments")
                        .HasForeignKey("DelegateEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.LeaveRequest", "LeaveRequest")
                        .WithMany("ManagerDelegations")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IK.Web.Models.Employee", "ManagerEmployee")
                        .WithMany("ManagerDelegations")
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.Web.Models.ManagerDelegation", "ParentManagerDelegation")
                        .WithMany("ChildDelegations")
                        .HasForeignKey("ParentManagerDelegationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DelegateEmployee");

                    b.Navigation("Department");

                    b.Navigation("LeaveRequest");

                    b.Navigation("ManagerEmployee");

                    b.Navigation("ParentManagerDelegation");
                });

            modelBuilder.Entity("IK.Web.Models.ApplicationRole", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("IK.Web.Models.Department", b =>
                {
                    b.Navigation("ChildDepartments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IK.Web.Models.Employee", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("CourseCertificates");

                    b.Navigation("DelegateAssignments");

                    b.Navigation("DirectReports");

                    b.Navigation("Documents");

                    b.Navigation("Educations");

                    b.Navigation("IdentityDocuments");

                    b.Navigation("ManagerDelegations");

                    b.Navigation("Phones");

                    b.Navigation("ProfilePhoto");

                    b.Navigation("Termination");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeCourseCertificate", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeDocumentCategory", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeEducation", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.EmployeeIdentityDocument", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveBalance", b =>
                {
                    b.Navigation("CarryOverWarning");

                    b.Navigation("RequestAllocations");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveCancellationRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("BalanceRefunds");
                });

            modelBuilder.Entity("IK.Web.Models.LeaveRequest", b =>
                {
                    b.Navigation("ApprovedDays");

                    b.Navigation("BalanceAllocations");

                    b.Navigation("CancellationRequests");

                    b.Navigation("ManagerDelegations");
                });

            modelBuilder.Entity("IK.Web.Models.ManagerDelegation", b =>
                {
                    b.Navigation("ChildDelegations");
                });
#pragma warning restore 612, 618
        }
    }
}
